apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx1
  labels: 
    type: engine
spec:
  replicas: 3 
  selector: 
    matchLabels:
      type: engine
  template: 
    metadata:
      name: nginx1
      labels:
        type: engine
    spec:
      containers:
        - name: nginx2
          image: nginx
          ports: 
            - containerPort: 80 
              hostPort: 8088
