apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    type: mynginx
spec:
  containers: 
    - name: mohan
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: rock
                operator: In
                values:
                  - mohan      
