apiVersion: v1
kind: Service
metadata: 
  name: jenkins-service
  labels: 
    type: proxy
spec:
  type: NodePort
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector: 
    type: proxy
    author: mohan


