apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels: 
    type: proxy
    author: mohan
spec: 
  containers: 
    - name: nginx-1
      image: nginx
      ports:
       - containerPort: 80
         hostPort: 80   
       
