apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat
  labels: 
    type: web
    
spec:
   replicas: 2
   selector:
     matchLabels:
       type: web
      
   template:
      metadata:
        name: tomcat
        labels:
          type: web
          
      spec:
        containers:
          - name: tomcat
            image: tomee
            ports: 
              - containerPort: 8080
                hostPort: 8080
