apiVersion: v1
kind: ReplicationController
metadata:
   name: httpd1
   labels: 
     type: proxy
spec:
   replicas: 2
   template: 
     metadata:
       name: httpd1
       labels:
         type: proxy
     spec:
       containers: 
         - name: httpd2
           image: httpd
           ports:
             - containerPort: 80
               hostPort: 80
