---
apiVersion: v1
kind: Secret
metadata:
  name: mine
  labels:
    type: mydb
type: opaque
stringData: 
   b: M2han
---

apiVersion: v1
kind: Pod
metadata:
  name: mydbs
  labels:
    type: dbs
spec:
  containers:
    - name: mysql
      image: mysql:5
      env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mine
              key: b
...
