---
apiVersion: v1
kind: Secret
metadata: 
  name: secret-key
  labels: 
    type: secret
    author: mohan
type: opaque
stringData: 
  a: Mohan 
---
apiVersion: v1
kind: Pod
metadata: 
  name: mydb
  labels: 
    type: db
spec:
  containers: 
    - name: mysql-1
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: a
...
