---
apiVersion: v1
kind: Secret
metadata:
  name: mySecret
  labels:
    type: db
type: opaque
stringData:
  a: Mohan  

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    type: mydb
spec:
  containers:
    - name: mysql1
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mySecret
              key: a
...                
