---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: web
spec:
  clusterIP: None
  ports:
    - port: 80
      name: node
  selector:
    app: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  labels:
    app: web
spec:
  replicas: 2
  selector:
    app: web
  serviceName: nginx
  template:    
    metadata:
      name: nginx
      labels:
        app: web 
    spec:  
      containers:
        - name: nginx-pod
          image: nginx
          ports: 
           - containerPort: 80
             name: node
          volumeMounts:   
            - name: myvolume
              mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
        - metadata:
            name: myvolume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
        
...
