apiVersion: v1
kind: Pod
metadata: 
  name: toleration
  labels:
    type: taint
spec: 
  containers: 
    - name: tol1
      image: nginx
  tolerations:
    - key: john1
      operator: Equal
      value: cena1
      effect: NoSchedule    
